Apply changes for core 4.3.0
priceline/design-system pull request #1001
Opened 2021-01-04 16:18 UTC by craigpalermo

2021-01-11 14:58 UTC, sdalonzo requested changes
Peers need to be careted. is 4.3 actually required?

2021-01-11 14:58 UTC, sdalonzo commented on packages/autocomplete/package.json
> +    "pcln-design-system": "4.3.0",
peers should never be this specific

2021-01-11 14:58 UTC, sdalonzo commented on packages/menu/package.json
> +    "pcln-design-system": "4.3.0",
same here.

2021-01-11 14:58 UTC, sdalonzo commented on packages/modal/package.json
> +    "pcln-design-system": "4.3.0",
and here

2021-01-11 14:58 UTC, sdalonzo commented on packages/popover/package.json
> +    "pcln-design-system": "4.3.0",
same

2021-01-11 14:58 UTC, sdalonzo commented on packages/slider/package.json
> +    "pcln-design-system": "4.3.0",
you get the idea ;)

2021-01-11 15:19 UTC, craigpalermo commented
> Peers need to be careted. is 4.3 actually required?

I don't think `4.3.0` is strictly required by any sub packages, but I think it makes sense to keep the peers up-to-date to encourage consumers to keep all of their DS-related packages at the latest instead of mixing versions within the same major because it seems like less work.

2021-01-11 18:11 UTC, sdalonzo approved these changes

2021-01-12 15:02 UTC, pcln-james commented on packages/core/CHANGELOG.json
> +            "author": "Craig Palermo <3260642+craigpalermo@users.noreply.github.com>",
weird most of our emails didn't work

2021-01-12 15:04 UTC, pcln-james approved these changes
LGTM but we should look into the email issue

2021-01-12 15:16 UTC, craigpalermo commented
> LGTM but we should look into the email issue

Oh yeah hmm, agreed. We'll have to look into that.

2021-01-12 15:21 UTC, merged