Update BackgroundImage to accept height as a number
priceline/design-system pull request #1006
Opened 2021-02-01 21:19 UTC by pcln-james

2021-02-01 21:25 UTC, pcln-barry approved these changes

2021-02-03 19:11 UTC, pcln-barry approved these changes

2021-02-03 19:16 UTC, craigpalermo requested changes

2021-02-03 19:16 UTC, craigpalermo commented on packages/core/src/BackgroundImage/BackgroundImage.js
> +  ]),
Could we replace this with `...height.propTypes`? Probably wouldn't hurt to do the same for `width`.

https://github.com/priceline/design-system/blob/7096fa92411261a21adf0c11c911d9e4a178c51e/packages/core/src/Text/Text.js#L91

2021-02-03 19:16 UTC, craigpalermo commented on packages/core/src/BackgroundImage/BackgroundImage.stories.js
>  export const Responsive = () => (
Can you add a responsive array for the `height` prop so we have an example of that?

2021-02-03 20:24 UTC, craigpalermo approved these changes

2021-02-03 20:27 UTC, merged