Use borderRadii from theme in all components
priceline/design-system pull request #1101
Opened 2022-01-10 18:57 UTC by craigpalermo

2022-01-10 18:59 UTC, craigpalermo commented on packages/core/src/theme/theme.js
> +  sm: '4px', // change all values EXCEPT FULL and NONE to 2px. Use these values in Brand.
- [ ] Change to 2px before merging

2022-01-11 21:42 UTC, sdalonzo commented on packages/core/src/Badge/Badge.stories.js
> +const Template = (args) => <Badge {...args}>badge</Badge>
ahhh so much nicer

2022-01-11 21:53 UTC, sdalonzo requested changes
just `rush change`

2022-01-12 13:59 UTC, sdalonzo approved these changes

2022-01-12 15:29 UTC, wesleymartin85 approved these changes

2022-01-12 15:33 UTC, merged