feat(pb-2681): adding experiences icon
priceline/design-system pull request #1235
Opened 2022-12-23 15:43 UTC by pricelyns

[PB-2681](https://priceline.atlassian.net/browse/PB-2681?atlOrigin=eyJpIjoiYjVhNDRlNDJkOTcwNDRmZDk5MjYzMzBhMzViODQ5NzgiLCJwIjoiaiJ9)
- adding icon for Experiences

2023-01-03 14:16 UTC, craigpalermo approved these changes

2023-01-03 14:20 UTC, craigpalermo requested changes
LGTM once you `rush change`

2023-01-03 19:17 UTC, craigpalermo approved these changes

2023-01-04 15:47 UTC, sangeethaathiyursridharan approved these changes

2023-01-04 15:48 UTC, danielryanbeck approved these changes

2023-01-09 17:01 UTC, merged