Add Grid component to pcln-design-system
priceline/design-system pull request #1303
Opened 2023-05-10 14:00 UTC by trenaryja

This PR introduces a new `Grid` component to the Design System. This is a primitive component, that exposes the [CSS Grid Specification](https://developer.mozilla.org/en-US/docs/Web/CSS/grid) in a react component, allowing for:
  - More complex layouts, especially in 2-dimensional designs (`Flex` is really only suited for 1-dimensional designs)
  - Nesting/Composing of layouts (Grids within Grids, or Gridception)
  - Gaps (independently control `rowGap` or `columnGap`, or both at the same time with the `gap` prop)

2023-05-25 19:51 UTC, sdalonzo commented on packages/core/src/Grid/__snapshots__/Grid.spec.tsx.snap
> +exports[`Grid renders correctly with default props 1`] = `
this serves no purpose

2023-05-26 01:26 UTC, sdalonzo requested changes
just lacking a changefile. this is a great MVP, and we can iterate as use cases present

2023-05-26 13:39 UTC, trenaryja commented
> just lacking a changefile. this is a great MVP, and we can iterate as use cases present

@sdalonzo Thanks for the reminder about the changefile! I've added that in now

2023-06-02 16:13 UTC, sdalonzo approved these changes

2023-06-02 19:53 UTC, craigpalermo approved these changes

2023-06-02 19:55 UTC, merged