Change withComponent to as prop
priceline/design-system pull request #990
Opened 2020-12-19 00:01 UTC by pcln-james

Resolves #989

2020-12-21 14:21 UTC, craigpalermo requested changes
LGTM so far, just one minor comment and need to create a change.

- [ ] Run `rush change`

2020-12-21 14:21 UTC, craigpalermo commented on packages/core/src/Text/Text.js
> +Text.p = ({ children, ...props }) => (
I think these are valid warnings, can you add a `displayName` to each of these?

2020-12-21 18:20 UTC, craigpalermo approved these changes

2020-12-29 17:24 UTC, gbellini911 approved these changes

2020-12-29 17:34 UTC, merged